version: '3.8'

services:
  # The FastAPI Application Service
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mounts the 'app' directory for live code reloading during development
      - ./app:/app/app
    env_file:
      - ./.env
    depends_on:
      - db

  # The PostgreSQL Database Service
  db:
    image: postgres:15
    volumes:
      # This creates a persistent volume for the database data
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      # Exposes the database port to the host machine for easy access with tools like pgAdmin
      - "5432:5432"

volumes:
  postgres_data:
